name: aurasync
description: "AuraSync connects your Android to your PC or Mac for remote control, mirroring and real-time data exchange via USB or local network."

version: 0.2.0+2
publish_to: "none"

homepage: https://softyes.com.br
repository: https://github.com/ZinChat/zinchat_mobile

environment:
  sdk: ^3.8.1
  flutter: ^3.32.1

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.3.4
  cupertino_icons: ^1.0.8
  aurasync_ui:
    path: ../aurasync_ui

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
